// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Return_Order_Portal.DataContext;

namespace Return_Order_Portal.Migrations
{
    [DbContext(typeof(ProcessContext))]
    [Migration("20210706063253_InitialMig")]
    partial class InitialMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Return_Order_Portal.Models.ProcessResponse", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackagingAndDeliveryCharge")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingCharge")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.ToTable("ProcessDb");
                });
#pragma warning restore 612, 618
        }
    }
}
